// <auto-generated />
using System;
using EcoEnergyRazorPages.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EcoEnergyRazorPages.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250323211238_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EcoEnergyRazorPages.Model.Simulation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<double>("EnergyGen")
                        .HasColumnType("float");

                    b.Property<decimal>("KWHCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("KWHPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<double>("Ratio")
                        .HasColumnType("float");

                    b.Property<double>("SunHours")
                        .HasColumnType("float");

                    b.Property<int>("SysType")
                        .HasColumnType("int");

                    b.Property<int>("SysTypeId")
                        .HasColumnType("int");

                    b.Property<double>("WaterFlow")
                        .HasColumnType("float");

                    b.Property<double>("WindVelocity")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Simulations");
                });
#pragma warning restore 612, 618
        }
    }
}
